from pathlib import Path
import json,re,html
from urllib.parse import quote
R=Path(__file__).resolve().parents[1]
source=(R/'scripts/site-base.html').read_text()
items=json.loads((R/'assets/collection.json').read_text())
# Mix occasions in the first screen; every original upload remains in the collection.
priority=['new-2','new-21','new-10','new-7','new-28','new-33','new-22','new-5','new-8','new-26','new-31','new-11']
items.sort(key=lambda i:priority.index(i['id']) if i['id'] in priority else 100)
(R/'assets/collection.json').write_text(json.dumps(items,ensure_ascii=False,indent=2))
wa=lambda title:'https://wa.me/917620644158?text='+quote('नमस्कार! मला '+title+' याबद्दल माहिती हवी आहे. / Hello, I would like to enquire about '+title+'.')
def image(i,eager=False,sizes='(max-width: 600px) 46vw, (max-width: 900px) 45vw, 29vw'):
 if 'copies' in i: srcset=', '.join(f"{v['path']} {v['width']}w" for v in i['copies'].values())
 else: srcset=f"{i['thumb']} 640w, {i['src']} {i['width']}w"
 return f'''<img src="{i['thumb']}" srcset="{srcset}" sizes="{sizes}" width="{i['width']}" height="{i['height']}" alt="{html.escape(i['title'])} — Sagar Flower Shop" {'fetchpriority="high"' if eager else 'loading="lazy"'} decoding="async">'''
def watermark(): return '<span class="watermark" aria-hidden="true">SAGAR · 7620644158</span>'
logo='<img class="shop-logo" src="assets/brand/sagar-logo.webp" alt="सागर फूल सेंटर — Sagar Flower Shop" width="420" height="211">'
head=source[:source.index('<body>')].replace('assets/images/bouquets/bouquets-25.webp','assets/images/bouquets/collection-02-1280.webp')
head=re.sub(r'<link rel="preload" as="image"[^>]+>', '<link rel="preload" as="image" href="assets/images/bouquets/collection-02-640.webp" imagesrcset="assets/images/bouquets/collection-02-360.webp 360w, assets/images/bouquets/collection-02-640.webp 640w, assets/images/bouquets/collection-02-1280.webp 967w" imagesizes="(max-width: 760px) 90vw, 42vw">',head)
ticker='सागर फ्लॉवर सेंटर मध्ये आपले स्वागत आहे! ऑर्डर देण्यासाठी कृपया खालील नंबरवर संपर्क साधा'
parts=[head, f'''<body><a class="skip" href="#main">Skip to content</a><div class="welcome-bar"><div class="ticker" aria-label="{ticker} 7620644158"><div class="ticker-track"><span lang="mr">✿ &nbsp; {ticker} &nbsp; <a href="tel:+917620644158">7620644158</a> &nbsp; ✿ &nbsp;</span><span aria-hidden="true" lang="mr">✿ &nbsp; {ticker} &nbsp; <b>7620644158</b> &nbsp; ✿ &nbsp;</span></div></div><button id="ticker-toggle" aria-label="Pause welcome ticker" aria-pressed="false">Ⅱ</button></div><header class="header"><a class="brand" href="#home" aria-label="Sagar Flower Shop home">{logo}</a><nav class="desktop-nav" aria-label="Main navigation"><a href="#collection" data-section="collection">Collection</a><a href="#films" data-section="films">Flower stories</a><a href="#services" data-section="services">Services</a><a href="#contact" data-section="contact">Visit us</a></nav><a class="button header-order" href="{wa('फुलांची ऑर्डर')}" target="_blank" rel="noopener noreferrer"><span>WhatsApp वर ऑर्डर</span><span aria-hidden="true">↗</span></a><div class="scroll-progress" aria-hidden="true"></div></header><main id="main">
<section class="hero wrap" id="home"><div class="hero-copy"><p class="eyebrow">PARLI, MAHARASHTRA <span>✳</span> FLOWERS FOR EVERY OCCASION</p><h1>Beautiful flowers.<br><em>शुभ क्षणांची साथ.</em></h1><p class="hero-description">Wedding garlands, heartfelt bouquets, and celebrations dressed in flowers. A little tradition. A whole lot of love.</p><div class="hero-actions"><a class="button" href="#collection">Explore the collection <span>↗</span></a><a class="text-link" href="tel:+917620644158">76206 44158 ↗</a></div><p class="hero-note" lang="mr">लग्नहार · बुके · गाडी सजावट · फुलांची सजावट</p></div>
<div class="hero-carousel" role="region" aria-roledescription="carousel" aria-label="Featured floral designs"><div class="hero-slides">''']
featured=[next(i for i in items if i['id']==id) for id in ['new-2','new-22','new-10','new-7']]
for n,i in enumerate(featured):
 parts.append(f'''<div class="hero-slide{' is-active' if n==0 else ''}" role="group" aria-roledescription="slide" aria-label="{n+1} of 4: {i['title']}" {'inert aria-hidden="true"' if n else ''}><button class="photo-button hero-photo" data-image="{i['src']}" data-title="{i['title']}" data-group="featured" aria-label="View {i['title']}">{image(i,n==0,'(max-width: 760px) 90vw, 42vw') if n==0 else image(i,False,'(max-width: 760px) 90vw, 42vw').replace(' src=', ' data-src=').replace(' srcset=', ' data-srcset=')}{watermark()}<span class="photo-hint">View full photo ↗</span></button></div>''')
parts.append('''</div><div class="hero-caption"><div><span class="eyebrow">THE SAGAR COLLECTION</span><p id="hero-caption">Rose embrace <small lang="mr">गुलाबांचा गुच्छ</small></p></div><div class="carousel-controls"><button class="hero-prev" aria-label="Previous featured design">←</button><button id="hero-pause" aria-label="Pause featured slideshow" aria-pressed="false">Ⅱ</button><button class="hero-next" aria-label="Next featured design">→</button></div></div><div class="hero-dots" role="group" aria-label="Choose featured design">''')
for n,i in enumerate(featured):parts.append(f'<button data-slide="{n}" aria-label="Show {i["title"]}" aria-pressed="{str(n==0).lower()}" class="{"active" if n==0 else ""}"></button>')
parts.append('''</div></div></section><div class="values-strip"><span>Made for your occasion</span><i>✳</i><span lang="mr">परंपरेचा सुगंध</span><i>✳</i><span>Nearby delivery</span></div>
<section id="collection" class="collection wrap section"><div class="section-heading"><div><p class="eyebrow">THE FLOWER EDIT · आमची फुलांची दुनिया</p><h2>Let the flowers<br><em>do the talking.</em></h2></div><p>Find a design you love. Tap to see every detail.<br><span lang="mr">तुमची आवड निवडा, बाकी आम्ही पाहतो.</span></p></div><div class="filters" role="group" aria-label="Filter floral collection">''')
for key,en,mr in [('all','All designs','सर्व'),('garlands','Wedding garlands','लग्नहार'),('bouquets','Bouquets','बुके'),('decor','Celebration décor','सजावट'),('belts','Floral jewellery','गजरा व कंबरपट्टा')]:
 parts.append(f'<button data-filter="{key}" aria-pressed="{str(key=="all").lower()}" class="{"active" if key=="all" else ""}"><span lang="mr">{mr}</span><small>{en}</small></button>')
parts.append(f'</div><div class="gallery-toolbar"><p id="filter-status" role="status" aria-live="polite">{len(items)} floral designs</p><span>Tap a photo to explore ↗</span></div><div class="portfolio">')
for i in items:
 parts.append(f'''<article class="work-card" data-category="{i['category']}"><button class="photo-button" data-image="{i['src']}" data-title="{i['title']}" data-group="collection" aria-label="View {i['title']}">{image(i)}{watermark()}<span class="expand" aria-hidden="true">↗</span></button><div class="card-info"><p class="eyebrow">{i['label']}</p><h3>{i['title']}</h3><p class="card-marathi" lang="mr">{i['marathi']}</p><a class="inquire" href="{wa(i['title'])}" target="_blank" rel="noopener noreferrer"><span>याबद्दल विचारा <small>Enquire</small></span><span aria-hidden="true">↗</span></a></div></article>''')
parts.append('''</div><div class="collection-footer"><button id="show-more" class="button button-outline" hidden>Discover more designs <span>↓</span></button><p>Have a colour, occasion or idea in mind?</p><a class="text-link" href="'''+wa('custom floral design')+'''" target="_blank" rel="noopener noreferrer">Let’s make it yours ↗</a></div></section>
<section id="films" class="films section"><div class="wrap"><div class="section-heading"><div><p class="eyebrow">A LITTLE MOVEMENT. A LOT OF FEELING.</p><h2>Flowers, <em>in motion.</em></h2></div><p lang="mr">फुलांची सुंदर झलक.<br><span lang="en">Tap to play a flower story.</span></p></div><div class="film-rail" tabindex="0" aria-label="Flower videos, swipe to explore">''')
videos=json.loads((R/'assets/videos.json').read_text())
for v in [videos[1],videos[2],videos[0]]:
 parts.append(f'''<article class="film-card"><div class="film-frame"><video id="video-{v['id']}" data-src="{v['src']}" preload="none" playsinline muted aria-label="{v['title']}"></video><img class="film-poster" src="{v['poster']}" alt="{v['title']} video preview" width="480" height="850" loading="lazy"><button class="video-play" aria-label="Play {v['title']}"><span aria-hidden="true">▶</span><small>WATCH THE STORY · 10 SEC</small></button>{watermark()}</div><div class="film-caption"><h3>{v['title']}</h3><p lang="mr">{v['marathi']}</p></div></article>''')
parts.append('''</div><div class="rail-footer"><span>← Swipe to discover →</span><div><button class="film-prev" aria-label="Scroll to previous video">←</button><button class="film-next" aria-label="Scroll to next video">→</button></div></div></div></section>
<section id="inspiration" class="inspiration section wrap"><div class="section-heading"><div><p class="eyebrow">IMAGINE YOUR OCCASION</p><h2>A little <em>inspiration.</em></h2></div><p>Fresh ideas for your celebration.<br>AI-created concepts to explore together.</p></div><div class="inspiration-grid">''')
for name,title,mr in [('varmala','The rose & lotus edit','गुलाब आणि कमळांची साथ'),('haldi','A golden haldi celebration','हळदीचा सोनेरी सोहळा')]:
 parts.append(f'''<article class="inspiration-card"><button class="photo-button" data-image="assets/images/inspiration/{name}-960.webp" data-title="{title} — AI design inspiration" data-group="inspiration" aria-label="View {title} inspiration"><img src="assets/images/inspiration/{name}-480.webp" srcset="assets/images/inspiration/{name}-480.webp 480w, assets/images/inspiration/{name}-960.webp 960w" sizes="(max-width: 600px) 85vw, 45vw" width="960" height="1280" alt="AI-created floral concept: {title}" loading="lazy"><span class="inspiration-badge">DESIGN INSPIRATION</span><span class="expand">↗</span></button><div class="inspiration-caption"><h3>{title}</h3><p lang="mr">{mr}</p><a class="text-link" href="{wa(title+' inspiration')}" target="_blank" rel="noopener noreferrer">Discuss a design like this ↗</a></div></article>''')
parts.append('</div></section>')
# Retain verified business and service content from the first version.
services=re.search(r'<section id="services".*?(?=<section id="story")',source,re.S).group()
story=re.search(r'<section id="story".*?(?=<section class="process)',source,re.S).group()
# Present the supplied garland photograph in full without cropping.
story=re.sub(r'<div class="story-image reveal">.*?</div>', '<div class="story-image"><img src="assets/images/garlands/collection-21-640.webp" width="640" height="1044" alt="Traditional rose and ivory garland by Sagar Flower Shop" loading="lazy">'+watermark()+'<div class="story-tag">परंपरेचा सुगंध.</div></div>',story, count=1,flags=re.S)
# Above replacement includes the original nested tag closure, remove the extra close.
story=story.replace('</div></div><div class="story-copy','</div><div class="story-copy')
contact=re.search(r'<section id="contact".*?</section>',source,re.S).group()
parts.extend([services,story,contact,'</main>'])
parts.append(f'''<footer><div class="wrap footer-top"><a class="brand" href="#home">{logo}</a><p lang="mr">तुमच्या आनंदात, फुलांची साथ.</p><a href="#home">Back to top ↑</a></div><div class="wrap footer-bottom"><span>© <span id="year">2026</span> Sagar Flower Shop</span><span>From Parli, with love. ✿</span></div></footer>''')
parts.append(re.search(r'<a class="floating-wa".*?(?=<nav class="mobile-nav")',source,re.S).group())
parts.append('''<nav class="mobile-nav" aria-label="Mobile navigation"><a href="#home" data-section="home" class="active"><span aria-hidden="true">⌂</span>Home</a><a href="#collection" data-section="collection"><span aria-hidden="true">❀</span>Collection</a><a href="#films" data-section="films"><span aria-hidden="true">▷</span>Stories</a><a href="#contact" data-section="contact"><span aria-hidden="true">♡</span>Contact</a></nav><dialog id="lightbox" aria-labelledby="lightbox-title"><button class="lightbox-close" aria-label="Close photo">×</button><div class="lightbox-image"><button class="lightbox-prev" aria-label="Previous photo">‹</button><img alt="" id="lightbox-photo"><span class="watermark" aria-hidden="true">SAGAR · 7620644158</span><button class="lightbox-next" aria-label="Next photo">›</button></div><div class="lightbox-bottom"><div><span id="lightbox-count" class="eyebrow"></span><h2 id="lightbox-title"></h2></div><a class="button" id="lightbox-inquire" target="_blank" rel="noopener noreferrer">WhatsApp ↗</a></div><p class="lightbox-tip">Swipe or use arrow keys · Zoom with your device</p></dialog></body></html>''')
(R/'index.html').write_text(''.join(parts))
print('Built redesigned portfolio with',len(items),'designs')
